include ./theme.conf

font_size 14.0
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
linux_display_server x11

wheel_scroll_multiplier 5.0
cursor_blink_interval 0
scrollback_lines 16384
detect_urls no
enable_audio_bell no
bell_on_tab no2
window_alert_on_bell no
visual_bell_duration 0.0
draw_minimal_borders yes
window_margin_width 0
bell_border_color #ff5a00
hide_window_decorations yes
sync_to_monitor yes
update_check_interval 0

map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
map ctrl+y paste_from_clipboard
# map Escape+w copy_to_clipboard

