music_directory	"~/audio/music"
# mpd own internal playlists
playlist_directory	"~/.mpd/playlists"
db_file		"~/.mpd/database"
log_file		"~/.mpd/log"
pid_file		"~/.mpd/pid"
state_file		"~/.mpd/state"
sticker_file		"~/.mpd/sticker.sql"
bind_to_address	"~/.mpd/socket"
# bind_to_address	"localhost"
log_level		"default"
metadata_to_use         "artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update	        "yes"
default_permissions     "read,add,control,admin"
filesystem_charset	"ASCII"
restore_paused 	"yes"
save_absolute_paths_in_playlists	"no"

input {
    plugin      "curl"
}

# for ncmpcpp music visualizer
audio_output {
   type            "fifo"
   name            "My FIFO"
   path            "/tmp/mpd.fifo"
   format          "44100:16:1"
}

audio_output {
	type		"pulse"
	name		"Pulse Output"
}
