music_directory		"~/audio/music"
playlist_directory	"~/audio/music"
db_file			"~/.mpd/database"
log_file		"~/.mpd/log"
pid_file		"~/.mpd/pid"
state_file		"~/.mpd/state"
sticker_file    "~/.mpd/sticker.sql"
bind_to_address		"localhost"
log_level		"default"
metadata_to_use         "artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update	        "yes"
default_permissions     "read,add,control,admin"
filesystem_charset	"ASCII"
# filesystem_charset  "UTF-8"

input {
        plugin          "curl"
}

# QOBUZ input plugin
input {
        enabled    "no"
        plugin     "qobuz"
#        app_id     "ID"
#        app_secret "SECRET"
#        username   "USERNAME"
#        password   "PASSWORD"
#        format_id  "N"
}

# TIDAL input plugin
input {
        enabled      "no"
        plugin       "tidal"
#        token        "TOKEN"
#        username     "USERNAME"
#        password     "PASSWORD"
#        audioquality "Q"
}


audio_output {
	type		"pulse"
	name		"Pulse Output"
}
