[Service]
# ExecStart=
# added in order for having complete bash environment loaded
# with emacs including full PATH, etc.
# ExecStart=/bin/bash -i -l -c "/usr/bin/emacs --fg-daemon"
ExecStop=

# make emacs stop without prompting user for saving recentf, buffers
# or anything else

#ExecStop=/usr/bin/emacsclient --eval "(let ((kill-emacs-hook (append kill-emacs-hook '(recentf-save-list)))) (save-buffers-kill-emacs t))"
ExecStop=/usr/bin/emacsclient --eval "(progn (setq kill-emacs-hook 'nil)(recentf-save-list)(amx-save-to-file)(save-buffers-kill-emacs t))"
# The location of the SSH auth socket varies by distribution, and some
# set it from PAM, so don't override by default.
# Environment=SSH_AUTH_SOCK=%t/keyring/ssh
