[Service]
Type=simple
# added in order for having complete bash environment loaded
# with emacs including full PATH, etc.
ExecStart=
ExecStart=/bin/bash -l -c '/bin/emacs --fg-daemon'
ExecStop=/bin/emacsclient --eval "(kill-emacs)"
# The location of the SSH auth socket varies by distribution, and some
# set it from PAM, so don't override by default.
# Environment=SSH_AUTH_SOCK=%t/keyring/ssh
Restart=on-failure
